### ISSUE TITLE
swal2-modal missing margins for @media screen width less than 500px

### ISSUE THREAD

**Issue by mumairali** [limonte/sweetalert2#132]
Sweetalert2 is not that responsive on mobile displays such as sweetalert(old). I have attached screenshot to get better idea,

![image](https://cloud.githubusercontent.com/assets/6498132/15283006/b523f0be-1b60-11e6-95e1-9833ee9c8a62.png)

**Comment by rafael-renan-pacheco** [comment]
Did you mean sweetalert2 doesn't have left and right margin on mobile displays?

From your screenshots, both seems responsive.

:+1:

**Comment by mumairali** [comment]
@rafael-renan-pacheco you are right about responsive. Margins are missing that's why it look ugly. Can you please provide me quick solution to fix this. Because it inject `<style>...</style>` tag in page upon rendering which miss some properties:

```
margin-left: 15px
margin-right: 15px
left: 0
right: 0
width: auto
```

above properties I copied from old version of sweetalert lib

**Comment by rafael-renan-pacheco** [comment]
As you can see here:

```css
@media screen and (max-width: 500px) {
    .swal2-modal {
        max-width: 100%;
        left: 0 !important;
        margin-left: 0 !important;
    }
}
```

sweetalert2 is forcing 0 margin. In order to overwrite that, you must have this same css selector in your custom css file, and change margin-left to 15px !important, and margin-right as well.

Maybe this 15px margin could be de default margin for 500px or less, but this is up to @limonte 

Until then, you can always overwrite that css.

:+1:
