### ISSUE TITLE
[Suggestion] Reduce title line-height

### ISSUE THREAD

**Issue by simshaun** [limonte/sweetalert2#396]
The current title line-height of 60px causes too much spacing for multi-line titles.

![image](https://cloud.githubusercontent.com/assets/379519/21699325/31323bb4-d369-11e6-80af-64f663aea0c7.png)

It would be nice if it were reduced.

I presume the current value is to provide some whitespace underneath. If so, then it could be replaced with a margin or padding.

**Comment by toverux** [comment]
Couldn't agree more. Each time I install SweetAlert in a project, I'm overwriting the title's line-height :smile:

**Comment by limonte** [comment]
Agree, `40px`?

**Comment by simshaun** [comment]
Yea that would be a lot better,

![image](https://cloud.githubusercontent.com/assets/379519/21726852/81f58486-d40c-11e6-8cca-2c456dbaad3e.png)

**Comment by toverux** [comment]
My vote would go for a relative line-height, in `em` or `%`. For example, in my last project, my style for SweetAlert is:

```scss
.swal2-modal {
    h2 {
        line-height: 110% !important;
        margin-bottom: 0.5em !important;
    }

    .btn { margin: 0 5px; }
}
```

Plus, I find 40px to be a bit too much :p
