### ISSUE TITLE
Buttons position swapped from original sweetalert...!?

### ISSUE THREAD

**Issue by malcolmocean** [limonte/sweetalert2#432]
My users (reasonably) complained that when I made this switch, the buttons switched sides, with Confirm now on the left instead of on the right.

Beyond believing that [confirm-on-the-right is superior](http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/), I also think that in terms of making it as easy as possible to switch from swal to swal2, you'll want to minimize stuff like this, or at least give an option for easily enabling the old behavior.

I have currently fixed this by using:

```css
.swal2-modal {
  direction: rtl;
}

.swal2-modal * {
  direction: ltr;
}
```
Which feels a little silly but it's the simplest way to un-surprise my users.
