### ISSUE TITLE
CSS file gets cut off in production

### ISSUE THREAD

**Issue by ivanvermeyen** [limonte/sweetalert2#464]
Hi, 

This is extremely weird.
On my live site, the compiled and minified CSS file get cut off right after this:

```css
@supports (-ms-accelerator:true){.swal2-range input{width:100%!important}.swal2-range output{display:none
```

When I remove the following `@supports` snippet and recompile, the complete file gets loaded...

```scss
@supports (-ms-accelerator: true) {
  .swal2-range {
    input {
      width: 100% !important;
    }

    output {
      display: none;
    }
  }
}
```

What's even more weird is that this only happens on the live site.
Locally it always get loaded completely.

**Edit:**

I'm using [Laravel Mix](https://laravel.com/docs/5.4/mix) to compile my CSS.
This issue only occurs when I compile and minify for production.
When I do a normal compile and don't minify, then the CSS is completely loaded.
Maybe this is more of a compile issue? (although the file is always complete on the servers, it just gets cut off when viewed in a browser)...
