### ISSUE TITLE
Whether z-index can be defined by itself

### ISSUE THREAD

**Issue by sxhjlzl** [limonte/sweetalert2#508]
If there are 2 dialog boxes，want to change z-index.

**Comment by limonte** [comment]
There coudn't be two swal2 dialogs at the same time by design.

In order to set `z-index` to a swal2 modal:

```css
.swal2-modal {
  z-index: 100;
}
```
