### ISSUE TITLE
Slider enhancement

### ISSUE THREAD

**Issue by stack-its** [limonte/sweetalert2#558]
On slider input:  would be nice if we had an option to show the units, also the number shown is a bit vertically misaligned with the slider graphic.

**Comment by limonte** [comment]
> On slider input: would be nice if we had an option to show the units

```css
.swal2-range output::after {
  content: "units";
}
```

> the number shown is a bit vertically misaligned with the slider graphic.

browser/OS?
