### ISSUE TITLE
swal doesn't support the IE11 for css3 flexbox.

### ISSUE THREAD

**Issue by Owenzh** [limonte/sweetalert2#580]
@nixta @pomartel @mockdeep  @Sontan @lipis 
Our team faces a issue that when the swal content too much, so the swal2-container too height, the content will be cut.
If we change the display into **block**, this is ok. Please help me to fix it. 

Thanks. 

```scss
.swal2-container {
  // centering
  **display: flex;**
  align-items: center;
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  padding: 10px;

  // backdrop
  background-color: transparent;

  z-index: 1060;

  &.swal2-fade {
    transition: background-color .1s;
  }

  &.swal2-shown {
    background-color: $overlay;
  }
}
```
